In [1]:
# khai báo thư viện 
import numpy as np
import seaborn as sns #Matplotlib mở rộng
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from google.colab import files
data = files.upload() 
# nhập dataset
dataset = pd.read_csv('iris.csv')
dataset.head() #in 5 hàng đầu

Saving iris.csv to iris (1).csv


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [12]:
# nhập dataset
# !gdown --id 1Qpns_vawemWLwziEsrAjR3NmAfiYyx4m
dataset = pd.read_csv("/content/drive/MyDrive/Bài tập AI/iris/iris.csv" )
dataset.head() #in 5 hàng đầu

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
from sklearn.metrics import confusion_matrix # 
from sklearn.metrics import classification_report #báo cáo
# Tách dữ liệu thành các biến phụ thuộc và độc lập 
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values

# Tách tập dữ liệu thành tập huấn luyện và tập kiểm tra 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # random_state tập test ngẫu nhiên

# Code dùng bằng SVM
#Support Vector Machine (SVM) là một thuật toán thuộc nhóm Supervised Learning (Học có giám sát)
from sklearn.svm import SVC

classifier = SVC(kernel='linear', probability=True) #Xác suất: Khi tạo lớp SVC để tính toán các ước tính xác suất bằng cách thiết lập probability=True:
classifier.fit(X_train, y_train) # phân lớp tập (X_train, y_train)
w = classifier.coef_ #hệ số
print('w = ', w)


# chú thích code :
#iloc :chọn đồng thời cả hai hàng và cột
# random_state : khởi tạo cho nó một cái mốc

w =  [[-1.84515263e-01 -2.03641805e-01  3.16826239e-02 -3.75150975e-01
  -1.39826546e-01]
 [-3.82131057e-02 -5.87893934e-04  4.40920450e-04 -2.71900944e-03
  -1.24927461e-03]
 [-7.43509721e-01 -3.71754861e-02  3.71754861e-02 -3.71754861e-01
  -2.23052916e-01]]


In [14]:
y_pred = classifier.predict(X_test) # dự đoán y_pred từ tập input X_test
print(y_pred)#in dự đoán
print()


['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa']



In [15]:
# so sánh độ chính xác
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

accuracy is 1.0


In [16]:
# Tóm tắt các dự đoán được thực hiện bởi trình phân loại 
print(classification_report(y_test, y_pred))
#Macro-average precision là trung bình cộng của các precision theo class
#weighted avg :trọng số trung bình

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [17]:
print(confusion_matrix(y_test, y_pred)) #Confusion Matrix ma trận nhầm lẫn hay ma trận lỗi


[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
