In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import numpy as np #thư viện numpy
import pandas as pd #thư viện đọc file csv
from sklearn import svm,metrics #thư viện ML trong đó SVM là một giải thuật và metrics để đánh giá mô hình phân loại
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import train_test_split

In [6]:
train = pd.read_csv('/content/sample_data/mnist_train_small.csv')# đọc file csv
train.head(8) # in ra 8 giá trị đầu tiên

6  0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0  5  0    0    0    0    0  ...      0      0      0      0      0      0
1  7  0    0    0    0    0  ...      0      0      0      0      0      0
2  9  0    0    0    0    0  ...      0      0      0      0      0      0
3  5  0    0    0    0    0  ...      0      0      0      0      0      0
4  2  0    0    0    0    0  ...      0      0      0      0      0      0
5  0  0    0    0    0    0  ...      0      0      0      0      0      0
6  6  0    0    0    0    0  ...      0      0      0      0      0      0
7  5  0    0    0    0    0  ...      0      0      0      0      0      0

[8 rows x 785 columns]

In [7]:
y_label = train['6'] # lấy cột label có nhãn 6
X_data = train.drop('6', axis = 1) #lấy các cột trừ cột label(6)
X_train_data = np.array(X_data)/255 # chia nhỏ tập dữ liệu dựa trên r,g,b[0,255]
print(X_train_data )


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
X_train,X_test,y_train,y_test = train_test_split(X_train_data,y_label,test_size=0.2)
# tập train sẽ lấy 80% cho tập train và 20% cho tập test.

In [9]:
# Code dùng bằng SVM
clf = svm.SVC(kernel='linear',C=100) # sử dụng tt SVM.SVC kiểu hồi quy tuyến tính với tham số phạt trong bài toán soft-mirgin là C 
clf.fit(X_train,y_train)# phân lớp tập (X_train, y_train)


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [10]:
y_pred = clf.predict(X_test)
#print(y_pred)#in dự đoán
print()# so sánh độ chính xác
print('accuracy score = ', metrics.accuracy_score(y_test,y_pred))
print(y_pred)#in dự đoán


accuracy score =  0.9085
[5 7 5 ... 2 3 5]
